services:
  - type: web
    name: image-processor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: CELERY_BROKER_URL
        value: pyamqp://admin:rabbitmqpass@rabbitmq:5672//

  - type: worker
    name: celery-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A celery_app worker --loglevel=info
    envVars:
      - key: CELERY_BROKER_URL
        value: pyamqp://admin:rabbitmqpass@rabbitmq:5672//

  - type: pserv
    name: rabbitmq
    env: docker
    dockerfilePath: ./Dockerfile.rabbitmq
    disk:
      name: rabbitmq-data
      mountPath: /var/lib/rabbitmq
      sizeGB: 1
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: admin
      - key: RABBITMQ_DEFAULT_PASS
        value: rabbitmqpass
